Fix TURN server in example server

diff --git a/Dockerfile.example b/Dockerfile.example
--- a/Dockerfile.example
+++ b/Dockerfile.example
@@ -239,8 +239,7 @@ RUN pip3 install --no-cache-dir --force-reinstall /opt/${PYPI_PACKAGE}-${PACKAGE
 ENV DISPLAY ":0"
 
 # Write startup script
-RUN TURN_RANDOM_PASSWORD="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 16)" && \
-    echo "#!/bin/bash -e\n\
+RUN echo "#!/bin/bash -ex\n\
 exec turnserver\n\
     --verbose\n\
     --listening-ip=0.0.0.0\n\
@@ -249,22 +248,21 @@ exec turnserver\n\
     --min-port=\${TURN_MIN_PORT:-49152}\n\
     --max-port=\${TURN_MAX_PORT:-65535}\n\
     --lt-cred-mech\n\
-    --user selkies:${TURN_RANDOM_PASSWORD}\n\
+    --user selkies:\${TURN_RANDOM_PASSWORD}\n\
     --no-cli\n\
     --allow-loopback-peers\n\
     --db /tmp/coturn-turndb\n\
     \${EXTRA_ARGS} \$@\n\
 " > /etc/start-turnserver.sh && chmod +x /etc/start-turnserver.sh && \
-    echo "#!/bin/bash -e\n\
+    echo "#!/bin/bash -ex\n\
 mkdir -pm700 /tmp/runtime-user\n\
 chown -f ubuntu:ubuntu /tmp/runtime-user\n\
 chmod -f 700 /tmp/runtime-user\n\
-/etc/start-turnserver.sh &\n\
 export DISPLAY=\"\${DISPLAY:-:0}\"\n\
 export LD_PRELOAD=\"selkies_joystick_interposer.so\${LD_PRELOAD:+:\${LD_PRELOAD}}\"\n\
 export SDL_JOYSTICK_DEVICE=/dev/input/js0\n\
-sudo-root mkdir -pm755 /dev/input || true\n\
-sudo-root touch /dev/input/js0 /dev/input/js1 /dev/input/js2 /dev/input/js3 || true\n\
+mkdir -pm755 /dev/input || sudo-root mkdir -pm755 /dev/input || echo 'Failed to create joystick interposer directory'\n\
+touch /dev/input/js0 /dev/input/js1 /dev/input/js2 /dev/input/js3 || sudo-root touch /dev/input/js0 /dev/input/js1 /dev/input/js2 /dev/input/js3 || echo 'Failed to create joystick interposer devices'\n\
 Xvfb -screen :0 8192x4096x24 +extension \"COMPOSITE\" +extension \"DAMAGE\" +extension \"GLX\" +extension \"RANDR\" +extension \"RENDER\" +extension \"MIT-SHM\" +extension \"XFIXES\" +extension \"XTEST\" +iglx +render -nolisten \"tcp\" -noreset -shmem 2>&1 >/tmp/Xvfb.log &\n\
 until [ -S /tmp/.X11-unix/X0 ]; do sleep 1; done && echo 'X Server is ready'\n\
 export PULSE_SERVER=unix:/tmp/runtime-user/pulse/native\n\
@@ -273,10 +271,14 @@ export PULSE_SERVER=unix:/tmp/runtime-user/pulse/native\n\
 [ \"\${START_XFCE4:-true}\" = \"true\" ] && rm -rf ~/.config/xfce4 && vglrun -d \"\${VGL_DISPLAY:-egl}\" +wm xfce4-session &\n\
 export SELKIES_ENCODER=\${SELKIES_ENCODER:-x264enc}\n\
 export SELKIES_ENABLE_RESIZE=\${SELKIES_ENABLE_RESIZE:-true}\n\
-export SELKIES_TURN_HOST=\${SELKIES_TURN_HOST:-\$(curl -fsSL checkip.amazonaws.com)}\n\
-export SELKIES_TURN_PORT=\${SELKIES_TURN_PORT:-3478}\n\
-export SELKIES_TURN_USERNAME=\${SELKIES_TURN_USERNAME:-selkies}\n\
-export SELKIES_TURN_PASSWORD=\${SELKIES_TURN_PASSWORD:-${TURN_RANDOM_PASSWORD}}\n\
+if [ -z \"\${SELKIES_TURN_HOST}\" || -z \"\${SELKIES_TURN_PORT}\" || ( -z \"\${SELKIES_TURN_SHARED_SECRET}\" && ( -z \"\${SELKIES_TURN_USERNAME}\" || -z \"\${SELKIES_TURN_PASSWORD}\" ) ) ]; then\n\
+  TURN_RANDOM_PASSWORD=\"\$(tr -dc A-Za-z0-9 </dev/urandom | head -c 24)\"\n\
+  /etc/start-turnserver.sh &\n\
+  export SELKIES_TURN_HOST=\$(curl -fsSL checkip.amazonaws.com)\n\
+  export SELKIES_TURN_PORT=\${SELKIES_TURN_PORT:-3478}\n\
+  export SELKIES_TURN_USERNAME=selkies\n\
+  export SELKIES_TURN_PASSWORD=\${TURN_RANDOM_PASSWORD}\n\
+fi\n\
 export SELKIES_TURN_PROTOCOL=\${SELKIES_TURN_PROTOCOL:-tcp}\n\
 export GST_DEBUG=\"*:2\"\n\
 export GSTREAMER_PATH=/opt/gstreamer\n\
