Minor edit

diff --git a/addons/example/Dockerfile b/addons/example/Dockerfile
--- a/addons/example/Dockerfile
+++ b/addons/example/Dockerfile
@@ -314,9 +314,9 @@ SHELL ["/bin/sh", "-c"]
 
 USER 0
 # Enable sudo through sudo-root with uid 0
-RUN if [ -d /usr/libexec/sudo ]; then SUDO_LIB="/usr/libexec/sudo"; else SUDO_LIB="/usr/lib/sudo"; fi && \
+RUN if [ -d "/usr/libexec/sudo" ]; then SUDO_LIB="/usr/libexec/sudo"; else SUDO_LIB="/usr/lib/sudo"; fi && \
     chown -R -f -h --no-preserve-root root:root /usr/bin/sudo-root /etc/sudo.conf /etc/sudoers /etc/sudoers.d /etc/sudo_logsrvd.conf "${SUDO_LIB}" || echo 'Failed to provide root permissions in some paths relevant to sudo' && \
-    chmod -f 4755 /usr/bin/sudo-root || echo 'Failed to set chmod with sudo-root'
+    chmod -f 4755 /usr/bin/sudo-root || echo 'Failed to set chmod for sudo-root'
 USER 1000
 
 ENV PIPEWIRE_LATENCY="32/48000"
